### ISSUE TITLE
Dockerfile breakage on Ubuntu

### ISSUE THREAD

**Issue by tsutsu** [covalenthq/bsp-geth#25]
Paraphrasing Discord user `soph#5873` in the Covalent Discord:

> `docker-compose-testnet.yml` is seemingly broken — it works on macOS, but not on Ubuntu 20.04.
>
> ```
> services.agent.depends_on contains an invalid type, it should be an array
> services.geth.depends_on contains an invalid type, it should be an array
> ```
>
> The apparent fix is to downgrade the Dockerfile version from `3` to `2.1`.
>
> See this thread: https://github.com/moby/moby/issues/30404

**Comment by sudeepdino008** [comment]
fixed here - https://github.com/covalenthq/bsp-geth/pull/26
